### ISSUE TITLE
Potential error in the epg code.

### ISSUE THREAD

**Issue by chiroptical** [chenhuang3/Embedding-Potential#1]
In `abinit-7.10.4_epg/src/94_scfcv/scfcv_emb.F90`, line 234 should read: `use interfaces_94_scfcv, except_this_one => scfcv_emb`. Otherwise, you get:

```
Error: 'scfcv_emb' of module 'interfaces_94_scfcv', imported at (1), is also the name of the current program unit
```

Compiled with GCC 4.8.5 and OpenMPI 2.0.2

**Comment by chenhuang3** [comment]
fixed and new code uploaded.  thanks a lot!
